GET http://localhost:3000/api/clientes 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozMiwidXNlcl9yb2xlIjoiYWRtaW4iLCJleHAiOjE2NzY1NjYwMTUsImlhdCI6MTY3MzU0MjAxNX0.VN2s4cfkCD-skAIKS8R-Vs6PiCCBps6l02cz8HhLMPg
###
GET http://localhost:3000/api/clientes/31

###
GET http://localhost:3000/api/clientes/v3

###
GET http://localhost:3000/api/clientes/edad/56

###
POST http://localhost:3000/api/clientes
Content-Type: application/json


{
  "nombre": "Patricio",
  "apellidos": "Organos",
  "direccion": "65 Shopiko Mane",
  "email": "porgan454s1@gmail.ly",
  "edad": 25,
  "genero": "m",
  "cuota": "39.90",
  "fecha_nacimiento": "1994-10-13",
  "dni": "526984763h"
  }


###
PUT http://localhost:3000/api/clientes/31
Content-Type: application/json

{
  "nombre": "Ringo",
  "apellidos": "Clem",
  "direccion": "9 Monica Place",
  "email": "rclemu@tinyurl.com",
  "edad": 22,
  "genero": "m",
  "cuota": "39.90",
  "fecha_nacimiento": "1960-07-06",
  "dni": "427000097e"
}
###
DELETE http://localhost:3000/api/clientes/138


##################
# API PROFESORES #
##################

###
GET http://localhost:3000/api/profesores
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozMiwidXNlcl9yb2xlIjoiYWRtaW4iLCJleHAiOjE2NzM1MTIzNTcsImlhdCI6MTY3MzUxMjA1N30.LF0d1-g1Tnr0FtZQtx_-e4bnDIvOcNqAVp_MbaKzbP8

###
GET http://localhost:3000/api/profesores/10

###
GET http://localhost:3000/api/profesores/clientes 

###
GET http://localhost:3000/api/profesores/nombres

###
POST http://localhost:3000/api/profesores 
Content-Type: application/json

{
  "nombre": "Luis",
  "experiencia": 6
}

###

PUT http://localhost:3000/api/profesores/104
Content-Type: application/json

{
  "nombre": "Amela Gill",
  "experiencia": 12
}

###
DELETE http://localhost:3000/api/profesores/104

##################
# API EJERCICIOS #
##################

###
GET http://localhost:3000/api/ejercicios

###
GET http://localhost:3000/api/ejercicios/15